name: ZAP Baseline Scan on Public Website
 
on:
  push:
    branches:
      - main
jobs:
  zap-baseline-scan:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Set up ZAP
        uses: zaproxy/action-full-scan@v0.11.0
        with:
           docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
           target: 'https://www.zaproxy.org/'
           format: 'html'  # Output format (html, json)
           timeout: 300  # Timeout in seconds
 
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP-Report
          path: zap_report.html  # Adjust if using a different format
